### ISSUE TITLE
[0.06] Playing in DOS -- "couldn't load endscreen"

### ISSUE THREAD

**Issue by SenhorFlibble** [lavenderdotpet/LibreQuake#123]
I've tried the current 0.06 release (both full and lite) in [486quake](https://github.com/goshhhy/486quake) and [QDOS](http://dk.toastednet.org/QDOS/) in DOSBox. Both versions run fine in these ports, whereas I could not run them in the official _Quake_ v1.08, which immediately exits with the following error:

> Error: model progs/v_axe.mdl has a skin taller than 200.

QDOS seems to run completely as intended, it plays OGG music (although I cannot change the volume, apparently) and I've noticed no glitches whatsoever. 486quake is faster, but it plays no music, and in the full version I've seen occasional rendering glitches, like a door in e1m1 that becomes transparent at a certain distance.

Upon exit to DOS, both ports greet me with the message:

> couldn't load endscreen.

Which I guess it just missing from the PAK files? (_Open Quartz_ has one, albeit it's very simplistic.) I suppose you could create something like the [ENDOOM screen](https://github.com/freedoom/freedoom/pull/1236) from _Freed∞M_?

You probably are aware of the glitchy textures on the backpack that humanoid enemies drop, but I'm gonna mention it JIC.

Also, what's with the Ogre replacement model? I remember previous versions having this Deep One-like character, although IIRC it was not animated:
https://i.imgur.com/exojmvI.png

**Comment by MissLavender-LQ** [comment]
correct it works in qdos and 486 but quake.exe (dos quake) is not supported due to the hight limit
we support those other dos ports and winquake

**Comment by MissLavender-LQ** [comment]
the backpack isnt a glitchy texture its just the blender uv colour grid since i havnt textured it yet

**Comment by MissLavender-LQ** [comment]
the newer ogre model is unfinished

**Comment by MissLavender-LQ** [comment]
ill have to lookinto the end screen thing
i think it might be fixed in this commit https://github.com/MissLavender-LQ/LibreQuake/commit/43a0c681ae334aab29bb481f9bc5bdaf1b5c3a33

**Comment by MissLavender-LQ** [comment]
anyways good night ill check the end thing when i wake up

**Comment by MotoLegacy** [comment]
I'm going to close this as the main issue at hand here has been resolved and the conversation seems to have ended.
