### ISSUE TITLE
More placeholder sounds from Freed∞M & Blasphemer?

### ISSUE THREAD

**Issue by SenhorFlibble** [lavenderdotpet/LibreQuake#124]
A while ago I compiled a selection of placeholder sounds to fill in the missing gaps in Open Quartz, for my personal use, from the Freed∞M & Blasphemer sounds. As far as I can tell, the licensing in both projects should make them compatible with LibreQuake. These include entire sound sets for the Ogre, the Death Knight, the Zombie, the Shambler, boss1 and boss 2, as well as some sounds from the plats and doors folders.

If you want, I could upload them and make a PR. I believe that placeholders are better than no sounds at all, and I tried to make the sets sound at least remotely consistent for each monster (although YMMV I guess).

Also an a related note, it was mentioned in a discussion of a different issue that although GPL assets are not compatible with the LibreQuake license, they could be included in actual binary releases with a note that some assets are licensed differently. If I understood this correctly, I was again thinking about placeholders -- Open Quartz has a reasonably workable "ghost knight" stand-in, and there is a GPL Ogre model (which somehow did not end up in the Open Quartz project, although I think that it was created for it) that can be found [here](https://freegamearts.tuxfamily.org/fga-item.php?sort=name&filter=model&search=&name=Brutus). Granted, they absolutely fall out of the general art style, but from the player's perspective a fully animated enemy model should be more preferable to a static silhouette that is much less readable and provides far less real-time feedback to the player. I'm suggesting this only because LibreQuake is already very playable with a good number of well-designed, interesting levels, and having a full set of game assets, even with a proportion of placeholders among them, would provide an almost-complete playing experience for the time being.

**Comment by MissLavender-LQ** [comment]
we already use freedoom sounds and assets and i have digged through Blasphemer in the past & (we used to ship a quake wad of Blasphemer's textures)

when librequake first started we were going to base apon OpenQuartz the original name was even LibreQuartz but that was changed to be bsd3 based and so able to freely share assets between freedoom and librequake 
i personally do not wish to pack openquartz assets with librequake at this point 

we are also currently refactoring how we handle sounds and assets in general

**Comment by MissLavender-LQ** [comment]
also me saying this isnt trying to shut down the idea 
if u want to send a pull req with freedoom and blasphemer sounds please go ahead

**Comment by MissLavender-LQ** [comment]
also i find it fun that u wrote freedoom with the ∞ like the logo

**Comment by SenhorFlibble** [comment]
> if u want to send a pull req with freedoom and blasphemer sounds please go ahead

Alright, did that just now. Thanks!

> also i find it fun that u wrote freedoom with the ∞ like the logo

Well, I originally [pitched the idea of that logo design](https://www.doomworld.com/forum/post/1532056), so I try to stick to it in writing too. I think it works fine with most fonts.

**Comment by MotoLegacy** [comment]
Closing as the PR has been opened and merged.
