### ISSUE TITLE
Gib scale style choice 

### ISSUE THREAD

**Issue by lavenderdotpet** [lavenderdotpet/LibreQuake#132]
quakes head gibs are a bit larger in scale then the monsters they come from
i imagin it was done this way either because the scale was off and they didn't notice 
or to give *gibbing*  some extra *Pow* / powerful feeling to it
it does look a bit off since they are so much larger the the monsters normal heads

**Comment by Calinou** [comment]
- Related to https://github.com/MissLavender-LQ/LibreQuake/pull/133#issuecomment-2043035484.

**Comment by pnahratow** [comment]
Quoting myself from the linked MR

>  have looked at the original files before doing this. The heads are generally around 1.5 times the size of the original model. Which is quite a lot visually but I did that for all of the heads. It looks good in game except for the fiend, vore and dog replacement. Thats why they are scaled down a bit.
  All the heads are now either 1.5 the size or 1.25 the size of the original model.

With this I think the issue can be closed since I see no further discussion happening here. Also rescale would be trivial if this should change.
