### ISSUE TITLE
Better "Knight" and "Rottweiler" replacements

### ISSUE THREAD

**Issue by PhoenixBlade24** [lavenderdotpet/LibreQuake#137]
While I like most of the enemy replacements in LibreQuake, two that stick out to me as being rather poor and in need of improvement are the replacement models for the "Knight" and the "Rottweiler". The knights in LibreQuake stick out to me as not really fitting in with Quake's aesthetic, appearing to me more as half-naked dudes and belonging more to a Silent Hill game in terms of design. The replacement for the rottweiler, while fittingly creepy, also has garish colors and appears to clash with the rest of the environment a bit too much. Especially when playing in certain mods.

I believe these two enemy types should be redesigned to fit more in line with vanilla Quake. The knight replacement should look more like a knight, and the Rottweiler replacement could perhaps look more like a wolf. With dark navy fur, blood stains, and large fangs.

**Comment by PhoenixBlade24** [comment]
I would also like to provide some free sound effects for the Ogre and Knight-replacement. These were AI generated with a commercial license granted, and given the current limbo status of copyright regarding things generated with AI, I believe they are safe to use for a Free project such as this.

https://send.vis.ee/download/b19bd4d5f3bb3dbb/#c9f5AkMyZ1omXAsVqcb9EA

**Comment by MissLavender-LQ** [comment]
we will not be accepting ai stuff

sorry I havnt gotten back to you about Ur first post yet

still don't have a stable dev environment 
been moving
