### ISSUE TITLE
Dead Pixel spotted on Letter K

### ISSUE THREAD

**Issue by thatspacepirate** [lavenderdotpet/LibreQuake#166]
![image](https://github.com/user-attachments/assets/6d36027f-4bae-4e2e-af08-3dccd9cd7f76)
![image](https://github.com/user-attachments/assets/4c1df734-c7db-4926-97a1-c00e413a1724)

**Comment by MotoLegacy** [comment]
Over to Lav

**Comment by lavenderdotpet** [comment]
![image](https://github.com/user-attachments/assets/b18c1281-393e-4872-8ca2-b73b26e06371)
looks like its from the uppercase J

**Comment by lavenderdotpet** [comment]
pull req now open that fixes this issue https://github.com/lavenderdotpet/LibreQuake/pull/171
