### ISSUE TITLE
Document tools needed for full compile of maps, wad files, lmp, etc

### ISSUE THREAD

**Issue by kwadroke** [lavenderdotpet/LibreQuake#28]
Create a document that includes links to Downloads/Git repos/Websites for: 
- qbsp/vis/light
- qpakman
- whatever else is needed to compile/package

I've found these through trial and error, but others may not be so lucky. For instance, I tried https://github.com/id-Software/Quake-Tools but the map was all dark in game. Apparently I needed https://github.com/ericwa/ericw-tools/ or similar instead.

**Comment by MissLavender-LQ** [comment]
yeah its very easy for me to forget that people dont know about these tools
very used to the knowledge level of the discord quake community

**Comment by kwadroke** [comment]
Unfortunately that information is locked away from those who don't use Discord.

**Comment by MissLavender-LQ** [comment]
yeah sadly a lot of the internet is locked away like thar

**Comment by Calinou** [comment]
> I've found these through trial and error, but others may not be so lucky. For instance, I tried [id-Software/Quake-Tools](https://github.com/id-Software/Quake-Tools) but the map was all dark in game. Apparently I needed [ericwa/ericw-tools](https://github.com/ericwa/ericw-tools/) or similar instead.

The reference Quake tools are pretty much unused nowadays, with ericw-tools being the most popular tool nowadays.

**Comment by MissLavender-LQ** [comment]
my focus has been a bit scattered sry i havnt gotten to it yet 
have done some slight stuff but not a proper doc 
![image](https://github.com/MissLavender-LQ/LibreQuake/assets/51702517/8319e6ac-302d-49e0-9593-dae51c535031)

**Comment by kwadroke** [comment]
Been thinking about this for a while.
Is it possible to setup a Wiki here on GitHub? I wouldn't mind documenting some of this myself now that I'm a little bit more familiar with the toolset.

**Comment by MissLavender-LQ** [comment]
we could im just not sure how to setup gh wikis ill check later today if i remember 
sorry ive been so hit or miss on stuff really bad memory and other issues

**Comment by kwadroke** [comment]
No worries. Not an urgent matter.

**Comment by MissLavender-LQ** [comment]
wikis are enabled now u should be able to add to it

**Comment by MissLavender-LQ** [comment]
also let me know if ur able to add to the wiki wanna make sure ive got it set up right

**Comment by pnahratow** [comment]
I have added a wiki page with the most basic information
https://github.com/lavenderdotpet/LibreQuake/wiki/Building
Tell me if anything more is needed otherwise the issue can be closed.
